version: "3.9"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - db-data:/app/omniagent.db
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run frontend/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - streamlit

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  db-data:
  qdrant-data:
